// Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps, leave this file empty.

== Postdeployment steps

=== Test the deployment

After the stack operation completes, the following output values display on the *Outputs* tab of the AWS CloudFormation console.

|===
|Ouput |Description

|`RepoUrl` |URL of the CodeCommit repository that you can clone and edit to invoke the pipeline and application deployment.
|`CodePipelineUrl` |URL of the CodePipeline pipeline.
|===

After you deploy this Partner Solution, a build of the application starts. You can use your browser to navigate to the CodePipeline URL to observe the build process. After the build completes, the deployment process for the application creates a CloudFormation named `<Quick Start stack name>-Deploy` using the name you enter when launching this Partner Solution. 

The stack also includes an output parameter that can be used to view your deployed application:

|===
|Ouput |Description

|`ServerlessExampleApi` |API Gateway URL that exposes the application.
|===

After you deploy this Partner Solution, you can use the CodeCommit repository URL to clone the repo and modify the application. Changes pushed to the repository invoke CodePipeline and a deployment of the application.

== Best practices for using {partner-product-short-name} on AWS

This Partner Solution uses https://aws.amazon.com/serverless/sam/[AWS Serverless Application Model] to define and deploy an application. While you are able and encouraged to modify the application code, we recommend that you maintain the definition of the application in the AWS SAM template.